<?php

/**
 * Implementation of hook_menu().
 */
function ding_webtrends_2014_menu() {
  $items = array();

  $items['admin/config/ding/webtrends_2014'] = array(
    'title' => 'WebTrends 2014',
    'description' => 'Settings for the WebTrends analytics tool 2014.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_webtrends_2014_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_webtrends_2014.admin.inc',
  );

  return $items;
}

/**
* Implements hook_page_alter().
*/
function ding_webtrends_2014_page_alter(&$page) {

  $domain = variable_get('webtrends_2014_domain', FALSE);
  $onsitedoms = variable_get('webtrends_2014_onsitedoms', FALSE);
  $dcs_id = variable_get('webtrends_2014_dcs_id', FALSE);

  if (!$domain || !$dcs_id) {
    watchdog('ding_webtrends_2014', 'Ding Webtrends 2014 module not configured.', array(), WATCHDOG_NOTICE);
    return;
  }

  $script_path = base_path() . drupal_get_path('module', 'ding_webtrends_2014');

  $script = <<<EOT
window.webtrendsAsyncInit=function(){
    var dcs=new Webtrends.dcs().init({
        dcsid:"$dcs_id",
        domain:"statse.webtrendslive.com",
        timezone:1,
        i18n:true,
        adimpressions:true,
        adsparam:"WT.ac",
        offsite:true,
        download:true,
        downloadtypes:"avi,csv,doc,docx,exe,gzip,mp3,mp4,pdf,ppt,pptx,rar,txt,wav,xls,xlsx,zip",
        onsitedoms:"$onsitedoms",
        fpcdom:".$domain",
        plugins:{
            hm:{src:"//s.webtrends.com/js/webtrends.hm.js"},
            facebook:{src:"//s.webtrends.com/js/webtrends.fb.js"},
            yt:{src:"//s.webtrends.com/js/webtrends.yt.js"}
        }
        }).track();
};
(function(){
    var s=document.createElement("script"); s.async=true; s.src="$script_path/js/webtrends.min.js";
    var s2=document.getElementsByTagName("script")[0]; s2.parentNode.insertBefore(s,s2);
}());

EOT;

    $html = <<<EOT
<noscript><img alt="dcsimg" id="dcsimg" width="1" height="1" src="//statse.webtrendslive.com/$dcs_id/njs.gif?dcsuri=/nojavascript&amp;WT.js=No&amp;WT.tv=10.4.1&amp;dcssip=$domain"/></noscript>
EOT;

  drupal_add_js($script,
    array('type' => 'inline', 'scope' => 'footer', 'weight' => 99, 'cache' => TRUE)
  );

  $page['footer']['webtrends_2014']= array(
      '#type' => 'markup',
      '#markup' => $html,
   );
}
